# Generated by Django 5.0.6 on 2024-05-22 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_newuser_is_admin_newuser_is_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='newuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
