# Generated by Django 5.0.6 on 2024-05-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_newuser_is_admin_newuser_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
