# Generated by Django 5.0.6 on 2024-05-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_newuser_country_newuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
