# Generated by Django 5.0.6 on 2024-05-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_newuser_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
